package com.sid.app.verbpractice.enums

enum class VerbClass {
    REG_AR, REG_ER, REG_IR, AIR, OLIR, ABRIR, TER, VIR, FAZER, IAR, POR, DIZER, CABER, SEGUIR, CRER, COBRIR, DAR, ESTAR, GEAR, HAVER, IR, LER, QUERER, NEVAR, OUVIR, PERDER, PODER, VER, PROVER, RIR, SABER, SER, TOSSIR, TRAZER, VALER, ENGOLIR, FUGIR, GREDIR, EDIR, DIVERTIR, SERVIR, ENTIR, SAUDAR, REUNIR, ELIR, REMIR, EAR, OIBIR, ERIR, OER, VESTIR, DORMIR, TUIR, BUIR, STRUIR, PÔR, OIAR, ATIR, DELIR, GANIR, BARRIR, DESPIR, DOER, FALIR, ODIR, PRAZER, DEF_ORIR, ERVIR
}