package com.sid.app.verbpractice.enums

enum class VerbForm {
    PRES_IND, PRET_IND, IMP_IND, SIMP_PLUP_IND, FUT_IND, SIMP_FUT_IND, COND_IND, PRES_PERF, PLUP, FUT_PERF, COND_PERF, PRES_PROG, PRET_PROG, IMP_PROG, SIMP_PLUP_PROG, FUT_PROG, COND_PROG, PRES_PERF_PROG, PLUP_PROG, FUT_PERF_PROG, COND_PERF_PROG, PRES_SUBJ, PRES_PERF_SUBJ, IMP_SUBJ, PLUP_SUBJ, FUT_SUBJ, FUT_PERF_SUBJ, IMP_AFF, IMP_NEG, PERS_INF
}